### ISSUE TITLE
DummyException

### ISSUE THREAD

**Issue by dawadam** [KnpLabs/KnpJsonSchemaBundle#19]
When we want to see shema like exemple :

http://domain.com/schemas/huitre.json

ContextErrorException: Notice: Undefined property: Knp\JsonSchemaBundle\HttpFoundation\JsonSchemaResponse::$encodingOptions in /vendor/knplabs/json-schema-bundle/src/Knp/JsonSchemaBundle/HttpFoundation/JsonSchemaResponse.php line 19

Symfony is 2.3.*

**Comment by NiR-** [comment]
[This PR](https://github.com/KnpLabs/KnpJsonSchemaBundle/pull/20) should fix the error. Thanks for the report.
