### ISSUE TITLE
PHP 5.4 short array syntax are being used on some files but the bundle should be compatible with PHP 5.3

### ISSUE THREAD

**Issue by pedropapa** [KnpLabs/KnpJsonSchemaBundle#24]
Just an example, on ```KnpJsonSchemaBundle/src/Knp/JsonSchemaBundle/DependencyInjection/Compiler/RegisterMappingsPass.php``` file on line 44 we can see that short array syntax has been used, this prevent KnpJsonSchema from working on systems with PHP 5.3.

In ```KnpJsonSchemaBundle/composer.json``` the PHP requirement for the bundle to work is marked as PHP 5.3 or above. You guys should update composer.json, changing from PHP 5.3 or above to PHP 5.4 or above OR refactor all occurrences of PHP 5.4+ syntax.

**Comment by stanlemon** [comment]
The other option is just change the array syntax, like https://github.com/KnpLabs/KnpJsonSchemaBundle/compare/master...stanlemon:php53

**Comment by pedropapa** [comment]
Yeah, this should solve the problem. Please make a pull request of this patch.
